version: '3.8'

services:
  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    networks:
      - api-network
    depends_on:
      - api-shared

  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
    networks:
      - api-network
    depends_on:
      - api-shared

  # gateway:
  #   build:
  #     context: ./gateway
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8080:8080"
  #   environment:
  #     - NODE_ENV=production
  #     - AUTH_SERVICE_URL=http://auth-service:3000
  #     - USER_SERVICE_URL=http://user-service:3001
  #   networks:
  #     - api-network
  #   depends_on:
  #     - auth-service
  #     - user-service

  api-shared:
    build:
      context: ./api-shared
      dockerfile: Dockerfile
    networks:
      - api-network

networks:
  api-network:
    driver: bridge 